# [Jacazul] Configure (PowerShell Version)

# Determine the absolute project root directory
$scriptDir = Split-Path $MyInvocation.MyCommand.Path -Parent
if (!$scriptDir) { $scriptDir = $PSScriptRoot }
$PROJECT_ROOT = (Resolve-Path (Join-Path $scriptDir "..\")).Path
$env:PROJECT_ROOT = $PROJECT_ROOT

# -----------------------------------------------------------------------------
# 0.0 Configure Language (Idiom) Preferences
# -----------------------------------------------------------------------------
$CONFIGURE_LANGUAGE = $false
if ($args -contains "--language") {
    $CONFIGURE_LANGUAGE = $true
}

$LANG_JSON = Join-Path $env:USERPROFILE ".jacazul-ai\language.json"

if (!(Test-Path $LANG_JSON) -or $CONFIGURE_LANGUAGE) {
    Write-Output "==================================="
    Write-Output "Language (Idiom) Configuration"
    Write-Output "==================================="
    Write-Output ""
    
    Write-Output "Options: portugues (pt-br), english (en), spanish (es)"
    $CHAT_LANG = Read-Host "What is the initial language do you want to talk (chat)? [pt-br]"
    if ([string]::IsNullOrWhiteSpace($CHAT_LANG)) { $CHAT_LANG = "pt-br" }
    
    $DATA_LANG = Read-Host "What is the initial language do you want to keep the input (everything generated by me)? [en]"
    if ([string]::IsNullOrWhiteSpace($DATA_LANG)) { $DATA_LANG = "en" }
    
    # Normalize inputs
    if ($CHAT_LANG -eq "portugues") { $CHAT_LANG = "pt-br" }
    if ($CHAT_LANG -eq "english") { $CHAT_LANG = "en" }
    if ($CHAT_LANG -eq "spanish") { $CHAT_LANG = "es" }
    
    if ($DATA_LANG -eq "portugues") { $DATA_LANG = "pt-br" }
    if ($DATA_LANG -eq "english") { $DATA_LANG = "en" }
    if ($DATA_LANG -eq "spanish") { $DATA_LANG = "es" }
    
    $langDir = Split-Path $LANG_JSON -Parent
    if (!(Test-Path $langDir)) {
        New-Item -ItemType Directory -Path $langDir -Force | Out-Null
    }
    
    $langObj = [PSCustomObject]@{
        chat = $CHAT_LANG
        data = $DATA_LANG
    }
    $langObj | ConvertTo-Json | Set-Content $LANG_JSON
    
    Write-Output ""
    Write-Output "[OK] Language preferences saved to $LANG_JSON"
    Write-Output ""
    
    if ($CONFIGURE_LANGUAGE) {
        return
    }
}

# -----------------------------------------------------------------------------
# 0.1 Configure Gemini CLI Settings
# -----------------------------------------------------------------------------
$GEMINI_BOOTSTRAP = Join-Path $PROJECT_ROOT "scripts\bootstrap\gemini.ps1"
if (Test-Path $GEMINI_BOOTSTRAP) {
    . $GEMINI_BOOTSTRAP
} else {
    Write-Warning "[WARNING] Gemini bootstrap script not found at $GEMINI_BOOTSTRAP."
}

# -----------------------------------------------------------------------------
# 0.2 Install Python Package (Entry Points)
# -----------------------------------------------------------------------------
$VENV_DIR = Join-Path $env:USERPROFILE ".jacazul-ai\.venv"
$VENV_BIN = Join-Path $VENV_DIR "Scripts"
if (!(Test-Path $VENV_BIN)) {
    Write-Output "[Jacazul] Initializing Python virtual environment..."
    $BOOTSTRAP_PYTHON = Join-Path $PROJECT_ROOT "scripts\bootstrap\python.ps1"
    if (Test-Path $BOOTSTRAP_PYTHON) {
        $env:DEBUG = "true"
        . $BOOTSTRAP_PYTHON
    }
}

# Ensure package is installed editable
$HasUv = [bool](Get-Command uv -ErrorAction SilentlyContinue)
$PipBin = Join-Path $VENV_BIN "pip.exe"
if ($HasUv) {
    Write-Output "[Jacazul] Installing Jacazul package via 'uv'..."
    & uv pip install -e "$PROJECT_ROOT"
} else {
    Write-Output "[Jacazul] Installing Jacazul package via 'pip'..."
    & $PipBin install -e "$PROJECT_ROOT"
}

# -----------------------------------------------------------------------------
# 0.3 Check Dependencies (Go & Cryptozoid)
# -----------------------------------------------------------------------------
if (!(Get-Command go -ErrorAction SilentlyContinue)) {
    Write-Error "[ERROR] 'go' is not installed. It is REQUIRED for security and platform tools."
    Write-Error "   Action: Please install Go (https://go.dev/doc/install) and try again."
    return
}

$CRYPTOZOID_BIN = Join-Path $env:USERPROFILE "go\bin\cryptozoid.exe"
if (!(Get-Command cryptozoid -ErrorAction SilentlyContinue) -and !(Test-Path $CRYPTOZOID_BIN)) {
    Write-Output "[Jacazul] 'cryptozoid' not found. Installing..."
    & go install github.com/idzoid/cryptozoid/cmd/cryptozoid@latest
}

# -----------------------------------------------------------------------------
# 0.4 Initialize Jacazul Vault (Security)
# -----------------------------------------------------------------------------
$VAULT_NAME = "jacazul-vault"
$VAULT_DIR = Join-Path $env:USERPROFILE ".jacazul-ai"
$PRIV_KEY = Join-Path $VAULT_DIR "${VAULT_NAME}_private.pem"

if (!(Test-Path $PRIV_KEY)) {
    Write-Output "[Jacazul] Initializing Jacazul Vault (EC P256)..."
    if (!(Test-Path $VAULT_DIR)) {
        New-Item -ItemType Directory -Path $VAULT_DIR -Force | Out-Null
    }
    
    $cryptozoidCmd = if (Get-Command cryptozoid -ErrorAction SilentlyContinue) { "cryptozoid" } else { $CRYPTOZOID_BIN }
    & $cryptozoidCmd ec generate -n "$VAULT_NAME" -p "$VAULT_DIR"
    Write-Output "[OK] Vault initialized at $VAULT_DIR"
}

# -----------------------------------------------------------------------------
# 1. Setup Sandbox Directory
# -----------------------------------------------------------------------------
$SANDBOX_DIR = Join-Path $PROJECT_ROOT "sandbox\copilot\.copilot"
Write-Output "Configuring sandbox directory at: $SANDBOX_DIR"
if (!(Test-Path $SANDBOX_DIR)) {
    New-Item -ItemType Directory -Path $SANDBOX_DIR -Force | Out-Null
}

# -----------------------------------------------------------------------------
# 2. Setup CLI links/wrappers in ~/bin
# -----------------------------------------------------------------------------
$BIN_DIR = Join-Path $env:USERPROFILE "bin"
if (!(Test-Path $BIN_DIR)) {
    Write-Output "Directory $BIN_DIR does not exist. Creating..."
    New-Item -ItemType Directory -Path $BIN_DIR -Force | Out-Null
}

$CLI_LINKS = @(
    "jacazul-gemini:scripts\jacazul-gemini.ps1",
    "jacazul-opencode:scripts\jacazul-opencode.ps1",
    "jacazul-copilot:scripts\jacazul-copilot.ps1",
    "jacazul-claude:scripts\jacazul-claude.ps1",
    "jacazul-pi:scripts\jacazul-pi.ps1",
    "tw-flow:$($VENV_BIN)\tw-flow.exe",
    "taskp:$($VENV_BIN)\taskp.exe",
    "ponder:$($VENV_BIN)\ponder.exe",
    "jacazul-hatch:$($VENV_BIN)\jacazul-hatch.exe",
    "jacazul-persona:$($VENV_BIN)\jacazul-persona.exe",
    "jacazul-github:scripts\jacazul-github.ps1",
    "jacazul-broker:$($VENV_BIN)\jacazul-broker.exe",
    "py-check:$($VENV_BIN)\py-check.exe"
)

foreach ($entry in $CLI_LINKS) {
    $parts = $entry -split ":", 2
    $linkName = $parts[0]
    $linkTarget = $parts[1]
    
    if (![System.IO.Path]::IsPathRooted($linkTarget)) {
        $linkTarget = Join-Path $PROJECT_ROOT $linkTarget
    }
    
    $wrapperPath = Join-Path $BIN_DIR "$linkName.ps1"
    Write-Output "Creating PowerShell wrapper for $linkName at $wrapperPath..."
    
    if ($linkTarget.EndsWith(".exe")) {
        $wrapperContent = '# [Jacazul] Wrapper for ' + $linkName + "`r`n" + '& "' + $linkTarget + '" $args'
    } else {
        $wrapperContent = '# [Jacazul] Wrapper for ' + $linkName + "`r`n" + '& powershell -NoProfile -ExecutionPolicy Bypass -File "' + $linkTarget + '" $args'
    }
    
    $wrapperContent | Set-Content $wrapperPath -Force
}

Write-Output ""
Write-Output "Setup complete! The following tools are available in ${BIN_DIR}:"
foreach ($entry in $CLI_LINKS) {
    $parts = $entry -split ":", 2
    Write-Output "  - $($parts[0])"
}
Write-Output ""
Write-Output "[INFO] TIP: Ensure $BIN_DIR is added to your user PATH environment variable to call these commands directly."
