<#
.SYNOPSIS
    Jacazul AI Environment Configuration Script
.DESCRIPTION
    Initializes language settings, python environment, security tools,
    and sets up command line aliases in %USERPROFILE%\bin.
#>

$ErrorActionPreference = "Stop"
$PROJECT_ROOT = (Resolve-Path "$PSScriptRoot\..").Path

# -----------------------------------------------------------------------------
# 0.0 Configure Language (Idiom) Preferences
# -----------------------------------------------------------------------------
$CONFIGURE_LANGUAGE = $false
if ($args -contains "--language") {
    $CONFIGURE_LANGUAGE = $true
}

$JACAZUL_DIR = "$env:USERPROFILE\.jacazul-ai"
$LANG_JSON = "$JACAZUL_DIR\language.json"

if (!(Test-Path $LANG_JSON) -or $CONFIGURE_LANGUAGE) {
    Write-Host "==================================="
    Write-Host "Language (Idiom) Configuration"
    Write-Host "==================================="
    Write-Host ""
    
    Write-Host "Options: portugues (pt-br), english (en), spanish (es)"
    $CHAT_LANG = Read-Host "What is the initial language do you want to talk (chat)? [pt-br]"
    if ([string]::IsNullOrWhiteSpace($CHAT_LANG)) { $CHAT_LANG = "pt-br" }
    
    $DATA_LANG = Read-Host "What is the initial language do you want to keep the input (everything generated by me)? [en]"
    if ([string]::IsNullOrWhiteSpace($DATA_LANG)) { $DATA_LANG = "en" }
    
    # Normalize inputs
    $langMap = @{
        "portugues" = "pt-br"
        "english"   = "en"
        "spanish"   = "es"
    }
    
    if ($langMap.ContainsKey($CHAT_LANG.ToLower())) { $CHAT_LANG = $langMap[$CHAT_LANG.ToLower()] }
    if ($langMap.ContainsKey($DATA_LANG.ToLower())) { $DATA_LANG = $langMap[$DATA_LANG.ToLower()] }

    if (!(Test-Path $JACAZUL_DIR)) { New-Item -ItemType Directory -Force -Path $JACAZUL_DIR | Out-Null }
    
    $langConfig = @{ chat = $CHAT_LANG; data = $DATA_LANG }
    $langConfig | ConvertTo-Json -Depth 2 | Set-Content $LANG_JSON -Encoding UTF8
    
    Write-Host "`n[v] Language preferences saved to $LANG_JSON`n"
    
    if ($CONFIGURE_LANGUAGE) {
        exit 0
    }
}

# -----------------------------------------------------------------------------
# 0.1 Configure Gemini CLI Settings
# -----------------------------------------------------------------------------
$GEMINI_BOOTSTRAP = "$PROJECT_ROOT\scripts\bootstrap\gemini.ps1"
if (Test-Path $GEMINI_BOOTSTRAP) {
    & $GEMINI_BOOTSTRAP
} else {
    Write-Warning "Gemini bootstrap script not found at $GEMINI_BOOTSTRAP."
}

# -----------------------------------------------------------------------------
# 0.2 Install Python Package (Entry Points)
# -----------------------------------------------------------------------------
$VENV_BIN = "$JACAZUL_DIR\.venv\Scripts"
if (!(Test-Path $VENV_BIN)) {
    Write-Host "[+] Initializing Python virtual environment..."
    try {
        & python -m venv "$JACAZUL_DIR\.venv"
    } catch {
        Write-Host "`n[-] ERRO: O comando 'python' nao foi encontrado ou falhou." -ForegroundColor Red
        Write-Host "-> Solucao: Certifique-se de ter o Python 3 instalado e configurado nas variaveis de ambiente do Windows." -ForegroundColor Yellow
        exit 1
    }
}

$uvPath = Get-Command uv -ErrorAction SilentlyContinue
if ($uvPath) {
    Write-Host "[+] Installing Jacazul package via 'uv'..."
    $env:VIRTUAL_ENV = "$JACAZUL_DIR\.venv"
    try {
        Start-Process -NoNewWindow -Wait -FilePath $uvPath.Source -ArgumentList @("pip", "install", "-e", ".") -WorkingDirectory $PROJECT_ROOT
    } catch {
        Write-Host "`n[-] ERRO: Falha ao executar 'uv'." -ForegroundColor Red
        exit 1
    }
} else {
    Write-Host "[+] Installing Jacazul package via 'pip'..."
    try {
        Start-Process -NoNewWindow -Wait -FilePath "$VENV_BIN\pip.exe" -ArgumentList @("install", "-e", ".") -WorkingDirectory $PROJECT_ROOT
    } catch {
        Write-Host "`n[-] ERRO: Falha ao instalar as ferramentas via pip local." -ForegroundColor Red
        exit 1
    }
}

# -----------------------------------------------------------------------------
# 0.3 Check Dependencies (Go & Cryptozoid)
# -----------------------------------------------------------------------------
$goPath = Get-Command go -ErrorAction SilentlyContinue
if (!$goPath) {
    Write-Host "`n[-] ERRO FATAL: Dependencia 'go' ausente." -ForegroundColor White -BackgroundColor DarkRed
    Write-Host "   Os binarios de seguranca como o Cryptozoid exigem a linguagem Golang instalada." -ForegroundColor Yellow
    Write-Host "   Solucao: Instale o Go acessando https://go.dev/doc/install, reinicie o terminal e tente novamente.`n" -ForegroundColor Yellow
    exit 1
}

$GO_BIN = "$env:USERPROFILE\go\bin"
$CRYPTOZOID_BIN = "$GO_BIN\cryptozoid.exe"

if (!(Get-Command cryptozoid -ErrorAction SilentlyContinue) -and !(Test-Path $CRYPTOZOID_BIN)) {
    Write-Host "[+] 'cryptozoid' (IdZoid) not found. Installing..."
    try {
        Start-Process -NoNewWindow -Wait -FilePath "go" -ArgumentList @("install", "github.com/idzoid/cryptozoid/cmd/cryptozoid@latest")
    } catch {
        Write-Host "`n[-] ERRO: A instalacao do 'cryptozoid' falhou." -ForegroundColor Red
        Write-Host "-> Solucao: Cheque sua conexao ou se o seu Golang esta configurado adequadamente ('go env')." -ForegroundColor Yellow
        exit 1
    }
}

if (($env:PATH -split ';') -notcontains $GO_BIN) {
    $env:PATH = "$GO_BIN;$env:PATH"
}

# -----------------------------------------------------------------------------
# 0.4 Initialize Jacazul Vault (IdZoid Security)
# -----------------------------------------------------------------------------
$VAULT_NAME = "jacazul-vault"
$VAULT_DIR = $JACAZUL_DIR
$VAULT_KEY = "$VAULT_DIR\${VAULT_NAME}_private.pem"

if (!(Test-Path $VAULT_KEY)) {
    Write-Host "[+] Initializing Jacazul Vault (EC P256)..."
    if (!(Test-Path $VAULT_DIR)) { New-Item -ItemType Directory -Force -Path $VAULT_DIR | Out-Null }
    
    $cryptozoidCmd = if (Test-Path $CRYPTOZOID_BIN) { $CRYPTOZOID_BIN } else { "cryptozoid.exe" }
    try {
        Start-Process -NoNewWindow -Wait -FilePath $cryptozoidCmd -ArgumentList @("ec", "generate", "-n", $VAULT_NAME, "-p", $VAULT_DIR)
        Write-Host "[v] Vault initialized at $VAULT_DIR"
    } catch {
        Write-Host "`n[-] ERRO FATAL: Falha ao gerar sua chave (Vault)." -ForegroundColor Red
        Write-Host "-> Solucao: Se o Cryptozoid acusar falta do binario, rode novamente." -ForegroundColor Yellow
        exit 1
    }
}

# -----------------------------------------------------------------------------
# 0.5 Persist Taskwarrior Binary Path (JACAZUL_REAL_TASK)
# -----------------------------------------------------------------------------
$LOCAL_TASK = Join-Path $PROJECT_ROOT "bin\tw\task.exe"
if (Test-Path $LOCAL_TASK) {
    Write-Host "[+] Persisting JACAZUL_REAL_TASK to User Environment..." -ForegroundColor Cyan
    $currentRealTask = [Environment]::GetEnvironmentVariable("JACAZUL_REAL_TASK", "User")
    
    if ($currentRealTask -ne $LOCAL_TASK) {
        [Environment]::SetEnvironmentVariable("JACAZUL_REAL_TASK", $LOCAL_TASK, "User")
        $env:JACAZUL_REAL_TASK = $LOCAL_TASK
        Write-Host "[v] JACAZUL_REAL_TASK set to $LOCAL_TASK" -ForegroundColor Green
    } else {
        Write-Host "[v] JACAZUL_REAL_TASK is already correctly set." -ForegroundColor Gray
    }
} else {
    Write-Warning "Local Taskwarrior binary not found at $LOCAL_TASK. Skipping persistence."
}

# -----------------------------------------------------------------------------
# 1. Setup Sandbox Directory
# -----------------------------------------------------------------------------
$SANDBOX_DIR = "$PROJECT_ROOT\sandbox\copilot\.copilot"
Write-Host "Configuring sandbox directory at: $SANDBOX_DIR"
if (!(Test-Path $SANDBOX_DIR)) { New-Item -ItemType Directory -Force -Path $SANDBOX_DIR | Out-Null }

# -----------------------------------------------------------------------------
# 2. Setup Wrapper Script in ~/bin
# -----------------------------------------------------------------------------
$BIN_DIR = "$env:USERPROFILE\bin"
if (!(Test-Path $BIN_DIR)) {
    Write-Host "Directory ~/bin does not exist. Creating..."
    New-Item -ItemType Directory -Force -Path $BIN_DIR | Out-Null
}

$TARGET_SCRIPT = "$BIN_DIR\copilot_sandboxed.cmd"
Write-Host "Creating wrapper script at $TARGET_SCRIPT..."

$wrapperContent = ""
$wrapperContent += "@echo off`n"
$wrapperContent += "set PROJECT_ROOT=$PROJECT_ROOT`n"
$wrapperContent += "set COPILOT_SANDBOXED_HOME=%PROJECT_ROOT%`n"
$wrapperContent += "call `"%PROJECT_ROOT%\scripts\copilot.cmd`" %*`n"

Set-Content -Path $TARGET_SCRIPT -Value $wrapperContent -Encoding ASCII

# -----------------------------------------------------------------------------
# 3. Setup CLI links in ~/bin
# -----------------------------------------------------------------------------
$CLI_LINKS = @(
    "jacazul-gemini:scripts\jacazul-gemini.ps1",
    "jacazul-opencode:scripts\jacazul-opencode.ps1",
    "jacazul-copilot:scripts\jacazul-copilot.ps1",
    "jacazul-claude:scripts\jacazul-claude.ps1",
    "python:scripts\python.cmd",
    "tw-flow:$JACAZUL_DIR\.venv\Scripts\tw-flow.exe",
    "taskp:$JACAZUL_DIR\.venv\Scripts\taskp.exe",
    "ponder:$JACAZUL_DIR\.venv\Scripts\ponder.exe",
    "jacazul-hatch:$JACAZUL_DIR\.venv\Scripts\jacazul-hatch.exe",
    "jacazul-persona:$JACAZUL_DIR\.venv\Scripts\jacazul-persona.exe",
    "jacazul-github:$JACAZUL_DIR\.venv\Scripts\jacazul-github.exe",
    "jacazul-broker:$JACAZUL_DIR\.venv\Scripts\jacazul-broker.exe",
    "py-check:$JACAZUL_DIR\.venv\Scripts\py-check.exe",
    "task:bin\tw\task.exe",
    "tw-calc:bin\tw\calc.exe",
    "tw-lex:bin\tw\lex.exe"
)

foreach ($entry in $CLI_LINKS) {
    $parts = $entry -split ':', 2
    $LINK_NAME = $parts[0]
    $LINK_TARGET = $parts[1]
    
    if (-not [System.IO.Path]::IsPathRooted($LINK_TARGET)) {
        $LINK_TARGET = "$PROJECT_ROOT\$LINK_TARGET"
    }
    
    $LINK_PATH = "$BIN_DIR\$LINK_NAME.cmd"
    Write-Host "[+] Updating CMD wrapper for $LINK_NAME..."
    $cmdContent = "@echo off`ncall `"$LINK_TARGET`" %*"
    
    if ($LINK_TARGET.EndsWith(".exe")) {
        $cmdContent = "@echo off`n`"$LINK_TARGET`" %*"
    } elseif ($LINK_TARGET.EndsWith(".ps1")) {
        $cmdContent = "@echo off`npowershell.exe -ExecutionPolicy Bypass -NoProfile -File `"$LINK_TARGET`" %*"
    }
    Set-Content -Path $LINK_PATH -Value $cmdContent -Encoding ASCII -Force
    Write-Host "[v] Link updated: $LINK_PATH"
}

Write-Host "`n[+] Ensuring $BIN_DIR is in your Windows User PATH..." -ForegroundColor Cyan
$userPath = [Environment]::GetEnvironmentVariable("Path", "User")
if (($userPath -split ';') -notcontains $BIN_DIR) {
    [Environment]::SetEnvironmentVariable("Path", "$userPath;$BIN_DIR", "User")
    Write-Host "[v] $BIN_DIR added to persistent User PATH." -ForegroundColor Green
} else {
    Write-Host "[v] $BIN_DIR is already in User PATH." -ForegroundColor Gray
}

Write-Host ""
Write-Host "Setup complete! The following tools are available in ~/bin:"
foreach ($entry in $CLI_LINKS) {
    $parts = $entry -split ':', 2
    Write-Host "  - $($parts[0])"
}

Write-Host "`n[i] IMPORTANT: Ensure $BIN_DIR is added to your Windows user %PATH% variable!" -ForegroundColor Yellow
